pod 'PureLayout'
#pod 'ZYQAssetPickerController'
pod 'DoImagePickerController'
#use_frameworks!
pod 'ReactiveCocoa', '~>2.5'
pod 'MWPhotoBrowser'
pod 'Mantle'
pod 'SDWebImage'
pod 'MBProgressHUD', '~> 0.9.2'
